nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ["Origin","Accept","content-type", "Authorization","X-Auth-Token"]
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
